In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/processed/credit_risk_cleaned.csv")
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [2]:
df["AGE_GROUP"] = pd.cut(
    df["AGE"],
    bins=[0, 30, 40, 50, 60, 100],
    labels=[1, 2, 3, 4, 5]
)

In [ ]:
bill_cols = ["BILL_AMT1","BILL_AMT2","BILL_AMT3","BILL_AMT4","BILL_AMT5","BILL_AMT6"]
df["TOTAL_BILL"] = df[bill_cols].sum(axis=1)
df["AVG_BILL"] = df[bill_cols].mean(axis=1)

In [ ]:
pay_amt_cols = ["PAY_AMT1","PAY_AMT2","PAY_AMT3","PAY_AMT4","PAY_AMT5","PAY_AMT6"]
df["TOTAL_PAYMENT"] = df[pay_amt_cols].sum(axis=1)
df["AVG_PAYMENT"] = df[pay_amt_cols].mean(axis=1)

In [ ]:
df["CREDIT_UTILIZATION"] = (
    df["TOTAL_BILL"] /
    (df["LIMIT_BAL"] + 1))  #very important feature to distinguish two customers who have same due but different limits

In [ ]:
df["PAYMENT_RATIO"] = (
    df["TOTAL_PAYMENT"] /
    (df["TOTAL_BILL"].abs() + 1))

In [7]:
df[
    [
        "AGE_GROUP",
        "TOTAL_BILL",
        "AVG_BILL",
        "TOTAL_PAYMENT",
        "AVG_PAYMENT",
        "CREDIT_UTILIZATION",
        "PAYMENT_RATIO"
    ]
].head()

,AGE_GROUP,TOTAL_BILL,AVG_BILL,TOTAL_PAYMENT,AVG_PAYMENT,CREDIT_UTILIZATION,PAYMENT_RATIO
0,1,7704,1284.000000,689,114.833333,0.385181,0.089422
1,1,17077,2846.166667,5000,833.333333,0.142307,0.292774
2,2,101653,16942.166667,11018,1836.333333,1.129465,0.108387
3,2,231334,38555.666667,8388,1398.000000,4.626587,0.036259
4,4,109339,18223.166667,59049,9841.500000,2.186736,0.540049

In [ ]:
pay_status_cols = ["PAY_0","PAY_2","PAY_3","PAY_4","PAY_5","PAY_6"]

df["AVG_DELAY"] = df[pay_status_cols].mean(axis=1)

df["MAX_DELAY"] = df[pay_status_cols].max(axis=1)

df["NUM_DELAY_MONTHS"] = (df[pay_status_cols] > 0).sum(axis=1)

In [ ]:
df["RECENT_DELAY_FLAG"] = (df["PAY_0"] > 0).astype(int)
#did the customer recently missed a payment?

In [ ]:
df["BILL_GROWTH"] = (df["BILL_AMT1"] - df["BILL_AMT6"])
#Large positive growth may indicate worsening financial behaviour

In [ ]:
df["PAYMENT_STD"] = (df[pay_amt_cols].std(axis=1))
#we did this to check how consistently the customer is paying his bills

NameError: name 'pay_amt_cols' is not defined

In [12]:
df[
    [
        "AVG_DELAY",
        "MAX_DELAY",
        "NUM_DELAY_MONTHS",
        "RECENT_DELAY_FLAG",
        "BILL_GROWTH",
        "PAYMENT_STD"
    ]
].head()

,AVG_DELAY,MAX_DELAY,NUM_DELAY_MONTHS,RECENT_DELAY_FLAG,BILL_GROWTH,PAYMENT_STD
0,-0.333333,2,2,1,3913,281.283072
1,0.500000,2,2,0,-579,752.772653
2,0.000000,0,0,0,13690,1569.815488
3,0.000000,0,0,0,17443,478.058155
4,-0.333333,0,0,0,-10514,13786.230736

In [13]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 30000
Columns: 38

In [14]:
df.to_csv(
    "../data/processed/credit_risk_feature_engineered.csv",
    index=False
)

print("Feature engineered dataset saved.")

Feature engineered dataset saved.